In [173]:
import numpy as np
import pandas as pd
import ast
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer

In [94]:
df=pd.read_csv("./data/after_preprocess.csv")

In [95]:
df

,Unnamed: 0,Title,Country,Type,Year,Ratings,Genre,Tags,Actors,Synopsis
0,0,Hidden Love,China,Drama,2023,9.2,"['Comedy', 'Romance', 'Youth']","['Caring Male Lead', 'Secret Crush', 'First Lo...","['Zhao Lu Si', 'Chen Zhe Yuan', 'Victor Ma']","Sang Zhi falls in love with Duan Jia Xu, the ..."
1,1,Move to Heaven,South Korea,Drama,2021,9.2,"['Life', 'Drama']","['Uncle-Nephew Relationship', 'Autism', 'Death...","['Lee Je Hoon', 'Tang Jun Sang', 'Hong Seung H...",Han Geu Roo is an autistic 20-year-old. He wo...
2,2,Nirvana in Fire,China,Drama,2015,9.1,"['Military', 'Historical', 'Drama', 'Political']","['Tragic Past', 'Power Struggle', 'Smart Male ...","['Hu Ge', 'Liu Tao', 'Wang Kai', 'Chen Long', ...","In sixth-century China, the Emperor of Great ..."
3,3,Weak Hero Class 1,South Korea,Drama,2022,9.1,"['Action', 'Youth', 'Drama']","['Violence', 'Friendship', 'Bromance', 'School...","['Park Ji Hoon', 'Choi Hyun Wook', 'Hong Kyung...",Yeon Shi Eun is a model student who ranks at ...
4,4,Hospital Playlist Season 2,South Korea,Drama,2021,9.1,"['Romance', 'Life', 'Drama', 'Medical']","['Multiple Mains', 'Band', 'Music', 'Multiple ...","['Jo Jung Suk', 'Yoo Yeon Seok', 'Jung Kyung H...",Everyday is extraordinary for five doctors an...
...,...,...,...,...,...,...,...,...,...,...
4988,4988,In a Relationship,Thailand,Drama,2022,6.8,['Romance'],"['Gay Male Lead', 'Short Length Series', 'Web ...","['Pea Pearanut Athicomnanta', 'Nine Trin Summa...","After losing an online match, a famous gamer ..."
4989,4989,In Love With a Rich Girl,Taiwan,Drama,2004,6.8,['Romance'],"['Sismance', 'Multiple Couples', 'Riches To Ra...","['Joe Chen', 'Jason Hsu']","Albee is a pampered, high-class young lady wh..."
4990,4990,My Mate Match,Thailand,Drama,2021,6.8,"['Comedy', 'Romance', 'Drama']","['Cohabitation', 'Gay Romance', 'LGBTQ+', 'Lov...","['Jet Jetsadakorn Bundit', 'Jame Kasama Khanja...",Match is looking for a roommate to share his ...
4991,4991,Ghost Runner,Thailand,Drama,2020,6.8,"['Thriller', 'Mystery', 'Romance', 'Supernatur...","['Ghost', 'Investigation', 'Suspense', 'Gay Ro...","['Link Thanawee Phongphasawat', 'Namo Jinna']",This is the story is surrounding Hart and Puk...
4992,4992,Orange Marmalade,South Korea,Drama,2015,6.8,"['Historical', 'Romance', 'Drama', 'Supernatur...","['Interspecies Romance', 'Music', 'High School...","['Kim Seol Hyun', 'Yeo Jin Goo', 'Lee Jong Hy...",Set in a fantasy world where humans and vampi...

In [96]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [97]:
df

,Title,Country,Type,Year,Ratings,Genre,Tags,Actors,Synopsis
0,Hidden Love,China,Drama,2023,9.2,"['Comedy', 'Romance', 'Youth']","['Caring Male Lead', 'Secret Crush', 'First Lo...","['Zhao Lu Si', 'Chen Zhe Yuan', 'Victor Ma']","Sang Zhi falls in love with Duan Jia Xu, the ..."
1,Move to Heaven,South Korea,Drama,2021,9.2,"['Life', 'Drama']","['Uncle-Nephew Relationship', 'Autism', 'Death...","['Lee Je Hoon', 'Tang Jun Sang', 'Hong Seung H...",Han Geu Roo is an autistic 20-year-old. He wo...
2,Nirvana in Fire,China,Drama,2015,9.1,"['Military', 'Historical', 'Drama', 'Political']","['Tragic Past', 'Power Struggle', 'Smart Male ...","['Hu Ge', 'Liu Tao', 'Wang Kai', 'Chen Long', ...","In sixth-century China, the Emperor of Great ..."
3,Weak Hero Class 1,South Korea,Drama,2022,9.1,"['Action', 'Youth', 'Drama']","['Violence', 'Friendship', 'Bromance', 'School...","['Park Ji Hoon', 'Choi Hyun Wook', 'Hong Kyung...",Yeon Shi Eun is a model student who ranks at ...
4,Hospital Playlist Season 2,South Korea,Drama,2021,9.1,"['Romance', 'Life', 'Drama', 'Medical']","['Multiple Mains', 'Band', 'Music', 'Multiple ...","['Jo Jung Suk', 'Yoo Yeon Seok', 'Jung Kyung H...",Everyday is extraordinary for five doctors an...
...,...,...,...,...,...,...,...,...,...
4988,In a Relationship,Thailand,Drama,2022,6.8,['Romance'],"['Gay Male Lead', 'Short Length Series', 'Web ...","['Pea Pearanut Athicomnanta', 'Nine Trin Summa...","After losing an online match, a famous gamer ..."
4989,In Love With a Rich Girl,Taiwan,Drama,2004,6.8,['Romance'],"['Sismance', 'Multiple Couples', 'Riches To Ra...","['Joe Chen', 'Jason Hsu']","Albee is a pampered, high-class young lady wh..."
4990,My Mate Match,Thailand,Drama,2021,6.8,"['Comedy', 'Romance', 'Drama']","['Cohabitation', 'Gay Romance', 'LGBTQ+', 'Lov...","['Jet Jetsadakorn Bundit', 'Jame Kasama Khanja...",Match is looking for a roommate to share his ...
4991,Ghost Runner,Thailand,Drama,2020,6.8,"['Thriller', 'Mystery', 'Romance', 'Supernatur...","['Ghost', 'Investigation', 'Suspense', 'Gay Ro...","['Link Thanawee Phongphasawat', 'Namo Jinna']",This is the story is surrounding Hart and Puk...
4992,Orange Marmalade,South Korea,Drama,2015,6.8,"['Historical', 'Romance', 'Drama', 'Supernatur...","['Interspecies Romance', 'Music', 'High School...","['Kim Seol Hyun', 'Yeo Jin Goo', 'Lee Jong Hy...",Set in a fantasy world where humans and vampi...

In [100]:
def convert(obj):
    list=[]
    for i in ast.literal_eval(obj):
        list.append(i)
    return list

In [101]:
df_copy=df

In [102]:
df_copy.Genre=df_copy.Genre.apply(convert)

In [103]:
type(df_copy.Genre[0])

list

In [105]:
df_copy.Tags=df_copy.Tags.apply(convert)

In [107]:
df_copy.Actors=df_copy.Actors.apply(convert)

In [108]:
type(df_copy.Actors[0])

list

In [110]:

df_copy.Synopsis=df_copy.Synopsis.apply(lambda x:x.split())

In [111]:
df_copy.Synopsis

0       [Sang, Zhi, falls, in, love, with, Duan, Jia, ...
1       [Han, Geu, Roo, is, an, autistic, 20-year-old....
2       [In, sixth-century, China,, the, Emperor, of, ...
3       [Yeon, Shi, Eun, is, a, model, student, who, r...
4       [Everyday, is, extraordinary, for, five, docto...
                              ...
4988    [After, losing, an, online, match,, a, famous,...
4989    [Albee, is, a, pampered,, high-class, young, l...
4990    [Match, is, looking, for, a, roommate, to, sha...
4991    [This, is, the, story, is, surrounding, Hart, ...
4992    [Set, in, a, fantasy, world, where, humans, an...
Name: Synopsis, Length: 4993, dtype: object

In [112]:
df_copy

,Title,Country,Type,Year,Ratings,Genre,Tags,Actors,Synopsis
0,Hidden Love,China,Drama,2023,9.2,"[Comedy, Romance, Youth]","[Caring Male Lead, Secret Crush, First Love, B...","[Zhao Lu Si, Chen Zhe Yuan, Victor Ma]","[Sang, Zhi, falls, in, love, with, Duan, Jia, ..."
1,Move to Heaven,South Korea,Drama,2021,9.2,"[Life, Drama]","[Uncle-Nephew Relationship, Autism, Death, Mou...","[Lee Je Hoon, Tang Jun Sang, Hong Seung Hee]","[Han, Geu, Roo, is, an, autistic, 20-year-old...."
2,Nirvana in Fire,China,Drama,2015,9.1,"[Military, Historical, Drama, Political]","[Tragic Past, Power Struggle, Smart Male Lead,...","[Hu Ge, Liu Tao, Wang Kai, Chen Long, Victor H...","[In, sixth-century, China,, the, Emperor, of, ..."
3,Weak Hero Class 1,South Korea,Drama,2022,9.1,"[Action, Youth, Drama]","[Violence, Friendship, Bromance, School Bullyi...","[Park Ji Hoon, Choi Hyun Wook, Hong Kyung, Kim...","[Yeon, Shi, Eun, is, a, model, student, who, r..."
4,Hospital Playlist Season 2,South Korea,Drama,2021,9.1,"[Romance, Life, Drama, Medical]","[Multiple Mains, Band, Music, Multiple Couples...","[Jo Jung Suk, Yoo Yeon Seok, Jung Kyung Ho, Ki...","[Everyday, is, extraordinary, for, five, docto..."
...,...,...,...,...,...,...,...,...,...
4988,In a Relationship,Thailand,Drama,2022,6.8,[Romance],"[Gay Male Lead, Short Length Series, Web Serie...","[Pea Pearanut Athicomnanta, Nine Trin Summasub]","[After, losing, an, online, match,, a, famous,..."
4989,In Love With a Rich Girl,Taiwan,Drama,2004,6.8,[Romance],"[Sismance, Multiple Couples, Riches To Rags, C...","[Joe Chen, Jason Hsu]","[Albee, is, a, pampered,, high-class, young, l..."
4990,My Mate Match,Thailand,Drama,2021,6.8,"[Comedy, Romance, Drama]","[Cohabitation, Gay Romance, LGBTQ+, Love Trian...","[Jet Jetsadakorn Bundit, Jame Kasama Khanjanaw...","[Match, is, looking, for, a, roommate, to, sha..."
4991,Ghost Runner,Thailand,Drama,2020,6.8,"[Thriller, Mystery, Romance, Supernatural]","[Ghost, Investigation, Suspense, Gay Romance, ...","[Link Thanawee Phongphasawat, Namo Jinna]","[This, is, the, story, is, surrounding, Hart, ..."
4992,Orange Marmalade,South Korea,Drama,2015,6.8,"[Historical, Romance, Drama, Supernatural]","[Interspecies Romance, Music, High School, Fir...","[Kim Seol Hyun, Yeo Jin Goo, Lee Jong Hyun]","[Set, in, a, fantasy, world, where, humans, an..."

In [113]:
df_copy.Tags=df_copy.Tags.apply(lambda x: [i.replace(" ","") for i in x])
df_copy.Genre=df_copy.Genre.apply(lambda x: [i.replace(" ","") for i in x])
df_copy.Actors=df_copy.Actors.apply(lambda x: [i.replace(" ","") for i in x])
# df_copy.Country=df_copy.Country.str.replace(" ","")

In [122]:
df_copy["exp1"]=df_copy.Synopsis+df_copy.Actors+df_copy.Tags+df_copy.Genre

In [123]:
df_copy.exp1[0]

['Sang',
 'Zhi',
 'falls',
 'in',
 'love',
 'with',
 'Duan',
 'Jia',
 'Xu,',
 'the',
 'boy',
 'who',
 'often',
 'comes',
 'to',
 'her',
 'house',
 'to',
 'play',
 'games',
 'in',
 'her',
 'older',
 'brotherâ€™s',
 'room.',
 'He',
 'is',
 'five',
 'years',
 'older',
 'than',
 'her.',
 'Sang',
 'Zhi',
 'had',
 'a',
 'crush',
 'on',
 'Duan',
 'Jia',
 'Xu',
 'when',
 'she',
 'was',
 'young,',
 'but',
 'they',
 'lost',
 'contact',
 'with',
 'each',
 'other',
 'for',
 'some',
 'reason.',
 'After',
 'she',
 'graduates,',
 'she',
 'joins',
 'the',
 'university',
 'in',
 'the',
 'city',
 'he',
 'is',
 'in,',
 'and',
 'during',
 'their',
 'day-to-day',
 'intimate',
 'and',
 'close',
 'interaction,',
 'they',
 'slowly',
 'fall',
 'in',
 'love.',
 'ZhaoLuSi',
 'ChenZheYuan',
 'VictorMa',
 'CaringMaleLead',
 'SecretCrush',
 'FirstLove',
 'Brother-SisterRelationship',
 'ComingOfAge',
 'NiceMaleLead',
 'ProtectiveMaleLead',
 'SteamyKiss',
 'AdaptedFromAWebNovel',
 'CaringFemaleLead',
 'Comedy',
 'Romance',
 'Youth']

In [124]:
df_copy[df_copy.Title==("Vincenzo")]

,Title,Country,Type,Year,Ratings,Genre,Tags,Actors,Synopsis,exp1
28,Vincenzo,South Korea,Drama,2021,8.9,"[Comedy, Law, Crime, Drama]","[Mafia, Revenge, SlightRomance, EccentricFemal...","[SongJoongKi, JeonYeoBeen, OkTaecYeon]","[At, the, age, of, eight,, Park, Joo, Hyeong, ...","[At, the, age, of, eight,, Park, Joo, Hyeong, ..."

In [125]:
df_copy.exp1=df_copy.exp1.apply(lambda x: " ".join(x))

In [128]:
df_copy.exp1

0       sang zhi falls in love with duan jia xu, the b...
1       han geu roo is an autistic 20-year-old. he wor...
2       in sixth-century china, the emperor of great l...
3       yeon shi eun is a model student who ranks at t...
4       everyday is extraordinary for five doctors and...
                              ...
4988    after losing an online match, a famous gamer c...
4989    albee is a pampered, high-class young lady who...
4990    match is looking for a roommate to share his n...
4991    this is the story is surrounding hart and pukp...
4992    set in a fantasy world where humans and vampir...
Name: exp1, Length: 4993, dtype: object

In [127]:
df_copy.exp1=df_copy.exp1.apply(lambda x: x.lower())

In [129]:
ps=PorterStemmer()

In [130]:
def stem(obj):
    y=[]
    for i in obj.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [131]:
df_copy.exp1=df_copy.exp1.apply(stem)

In [132]:
cv=CountVectorizer(max_features=5000,stop_words='english')

In [135]:
vector=cv.fit_transform(df_copy["exp1"]).toarray()

In [136]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [137]:
feature_names = cv.get_feature_names_out()

print(feature_names)

['000' '10' '100' ... 'zong' 'zu' 'zuo']

In [138]:
similarity=cosine_similarity(vector)

In [139]:
similarity

array([[1.        , 0.07491024, 0.03535258, ..., 0.07974522, 0.04175738,
        0.11922883],
       [0.07491024, 1.        , 0.09098699, ..., 0.04736317, 0.01653401,
        0.01049092],
       [0.03535258, 0.09098699, 1.        , ..., 0.10431037, 0.02731028,
        0.0693141 ],
       ...,
       [0.07974522, 0.04736317, 0.10431037, ..., 1.        , 0.15401028,
        0.07817631],
       [0.04175738, 0.01653401, 0.02731028, ..., 0.15401028, 1.        ,
        0.0818717 ],
       [0.11922883, 0.01049092, 0.0693141 , ..., 0.07817631, 0.0818717 ,
        1.        ]])

In [151]:
def drama_recommend(drama):
    drama_index=df_copy[df_copy.Title==drama].index[0]
    distance=similarity[drama_index]
    drama_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]
#     print(drama_list)
#     for i in drama_list:
#         print(df_copy.iloc[i[0]])
    nearest_drama = pd.DataFrame([df_copy.iloc[i[0]] for i in drama_list])
    return nearest_drama

In [156]:
drama_recommend('Itaewon Class')

,Title,Country,Type,Year,Ratings,Genre,Tags,Actors,Synopsis,exp1
2163,Tra Barb See Chompoo,Thailand,Drama,2018,7.7,"[Comedy, Romance, Life, Melodrama]","[Revenge, AggressiveMaleLead, LoveTriangle, Co...","[PonNawaschPhupantachsee, BuaNalinthipSakulong...","[Patsakorn, is, the, only, heir, of, a, millio...",patsakorn is the onli heir of a millionair who...
2444,Panthakan Rak,Thailand,Drama,2018,7.7,"[Comedy, Romance, Drama]","[SpoiledMaleLead, Love/HateRelationship, Stron...","[BankArtitTangwiboonpanit, MookMookdaNarinrak]","[Panthakan,, hi-so, godlike,, has, the, label,...","panthakan, hi-so godlike, ha the label of trag..."
647,Miss Crow with Mr. Lizard,China,Drama,2021,8.2,"[Business, Comedy, Romance, Fantasy]","[OptimisticFemaleLead, CarAccident, OlderMan/Y...","[RenJiaLun, XingFei, LiuRuiLin, ZhaoYiHuan]","[Gu, Chuan, is, a, passion-filled,, vibrant, y...","gu chuan is a passion-filled, vibrant young ma..."
771,Ore no Ie no Hanashi,Japan,Drama,2021,8.1,"[Comedy, Life, Drama, Family]","[FamilyRelationship, Father-SonRelationship, D...","[NagaseTomoya, TodaErika]","[Now, sidelined, due, to, injury, and, age,, f...","now sidelin due to injuri and age, former pro-..."
3383,49,Japan,Drama,2013,7.5,"[Comedy, Youth, Drama, Supernatural]","[Friendship, SlightRomance, FamilyRelationship...",[SatoShori],"[Dan, is, a, first, year, high, school, studen...",dan is a first year high school student. he is...

In [155]:
df_copy[df_copy.Title=="Itaewon Class"]

,Title,Country,Type,Year,Ratings,Genre,Tags,Actors,Synopsis,exp1
262,Itaewon Class,South Korea,Drama,2020,8.4,"[Business, Romance, Life, Drama]","[Revenge, TimeSkip, SmartFemaleLead, FemaleCha...","[ParkSeoJoon, KimDaMi, KwonNaRa, YooJaeMyung]","[Park, Saeroyi's, life, has, been, turned, ups...",park saeroyi' life ha been turn upsid down aft...

## 2nd recommendor

In [157]:
df_2=df_copy[['Title','Country','Year','Ratings']]

In [158]:
df_2["Tag"]=df_copy.Genre+df_copy.Tags+df_copy.Actors

C:\Users\Prashant Dahiya\AppData\Local\Temp\ipykernel_13120\3740788869.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2["Tag"]=df_copy.Genre+df_copy.Tags+df_copy.Actors

In [159]:
df_2

,Title,Country,Year,Ratings,Tag
0,Hidden Love,China,2023,9.2,"[Comedy, Romance, Youth, CaringMaleLead, Secre..."
1,Move to Heaven,South Korea,2021,9.2,"[Life, Drama, Uncle-NephewRelationship, Autism..."
2,Nirvana in Fire,China,2015,9.1,"[Military, Historical, Drama, Political, Tragi..."
3,Weak Hero Class 1,South Korea,2022,9.1,"[Action, Youth, Drama, Violence, Friendship, B..."
4,Hospital Playlist Season 2,South Korea,2021,9.1,"[Romance, Life, Drama, Medical, MultipleMains,..."
...,...,...,...,...,...
4988,In a Relationship,Thailand,2022,6.8,"[Romance, GayMaleLead, ShortLengthSeries, WebS..."
4989,In Love With a Rich Girl,Taiwan,2004,6.8,"[Romance, Sismance, MultipleCouples, RichesToR..."
4990,My Mate Match,Thailand,2021,6.8,"[Comedy, Romance, Drama, Cohabitation, GayRoma..."
4991,Ghost Runner,Thailand,2020,6.8,"[Thriller, Mystery, Romance, Supernatural, Gho..."
4992,Orange Marmalade,South Korea,2015,6.8,"[Historical, Romance, Drama, Supernatural, Int..."

In [160]:
df_2.Tag=df_2.Tag.apply(lambda x: " ".join(x))

C:\Users\Prashant Dahiya\AppData\Local\Temp\ipykernel_13120\1368889594.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2.Tag=df_2.Tag.apply(lambda x: " ".join(x))

In [161]:
df_2

,Title,Country,Year,Ratings,Tag
0,Hidden Love,China,2023,9.2,Comedy Romance Youth CaringMaleLead SecretCrus...
1,Move to Heaven,South Korea,2021,9.2,Life Drama Uncle-NephewRelationship Autism Dea...
2,Nirvana in Fire,China,2015,9.1,Military Historical Drama Political TragicPast...
3,Weak Hero Class 1,South Korea,2022,9.1,Action Youth Drama Violence Friendship Bromanc...
4,Hospital Playlist Season 2,South Korea,2021,9.1,Romance Life Drama Medical MultipleMains Band ...
...,...,...,...,...,...
4988,In a Relationship,Thailand,2022,6.8,Romance GayMaleLead ShortLengthSeries WebSerie...
4989,In Love With a Rich Girl,Taiwan,2004,6.8,Romance Sismance MultipleCouples RichesToRags ...
4990,My Mate Match,Thailand,2021,6.8,Comedy Romance Drama Cohabitation GayRomance L...
4991,Ghost Runner,Thailand,2020,6.8,Thriller Mystery Romance Supernatural Ghost In...
4992,Orange Marmalade,South Korea,2015,6.8,Historical Romance Drama Supernatural Interspe...

In [162]:
cv=CountVectorizer(max_features=5000,stop_words='english')

In [163]:
vector=cv.fit_transform(df_2["Tag"]).toarray()

In [164]:
similarity=cosine_similarity(vector)

In [169]:
def drama_recommend(drama):
    drama_index=df_2[df_2.Title==drama].index[0]
    distance=similarity[drama_index]
    drama_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[0:6]
#     print(drama_list)
#     for i in drama_list:
#         print(df_copy.iloc[i[0]])
    nearest_drama = pd.DataFrame([df.iloc[i[0]] for i in drama_list])
    return nearest_drama

In [170]:
drama_recommend('Itaewon Class')

,Title,Country,Type,Year,Ratings,Genre,Tags,Actors,Synopsis,exp1
262,Itaewon Class,South Korea,Drama,2020,8.4,"[Business, Romance, Life, Drama]","[Revenge, TimeSkip, SmartFemaleLead, FemaleCha...","[ParkSeoJoon, KimDaMi, KwonNaRa, YooJaeMyung]","[Park, Saeroyi's, life, has, been, turned, ups...",park saeroyi' life ha been turn upsid down aft...
102,Misaeng: Incomplete Life,South Korea,Drama,2014,8.7,"[Business, Life, Drama]","[WorkplaceAbuse, Teamwork, AdaptedFromAWebtoon...","[YimSiWan, LeeSungMin, KangSoRa, KangHaNeul, B...","[Jang, Geu, Rae, has, played, the, game, of, G...",jang geu rae ha play the game of go sinc he wa...
221,What's Wrong with Secretary Kim,South Korea,Drama,2018,8.5,"[Business, Comedy, Romance]","[Boss-EmployeeRelationship, RichMaleLead, Adap...","[ParkMinYoung, ParkSeoJoon]","[The, series, revolves, around, the, narcissis...",the seri revolv around the narcissist lee youn...
3905,Love Actually,China,Drama,2017,7.3,"[Business, Romance, Life, Drama]","[WorkplaceSetting, GeniusMaleLead, WorkplaceRo...","[JoeChen, TongDaWei, WangYiBo]","[Ding, Ren, Jian, is, a, married, man, with, a...",ding ren jian is a marri man with a child. he ...
603,Pegasus Market,South Korea,Drama,2019,8.2,"[Business, Comedy, Drama]","[AdaptedFromAWebtoon, EccentricMaleLead, Teamw...","[KimByungChul, LeeDongHwi]","[""Cheap, Cheonlima, Mart"", tells, the, story, ...","""cheap cheonlima mart"" tell the stori of emplo..."
2272,Backstreet Rookie,South Korea,Drama,2020,7.7,"[Action, Business, Comedy, Romance]","[HardworkingFemaleLead, BadassFemaleLead, Boss...","[JiChangWook, KimYooJung, HanSunHwa, DoSangWoo...","[Jung, Saet, Byul, is, a, 22-year-old,, beauti...","jung saet byul is a 22-year-old, beauti four-d..."

In [172]:
drama_recommend("Moment at Eighteen")

,Title,Country,Type,Year,Ratings,Genre,Tags,Actors,Synopsis,exp1
1013,Moment at Eighteen,South Korea,Drama,2019,8.0,"[Comedy, Romance, Life, Drama]","[FirstLove, HighSchool, ShyMaleLead, LoveTrian...","[OngSeongWu, KimHyangGi, ShinSeungHo, KangKiYo...","[Transfer, student, Jun, Woo, has, no, interes...",transfer student jun woo ha no interest in sch...
2167,My First First Love,South Korea,Drama,2019,7.7,"[Comedy, Romance, Life, Drama]","[NiceMaleLead, FirstLove, FriendsToLovers, Coh...","[KimJiSoo, JungChaeYeon, JungJinYoung, ChoiRi,...","[A, group, of, Yoon, Tae, Ohâ€™s, friends, sudde...",a group of yoon tae ohâ€™ friend suddenli move i...
1190,I Don't Love You Yet,Japan,Drama,2019,8.0,"[Comedy, Romance, Life, Drama]","[FriendsToLovers, SweetMaleLead, SuccessfulFem...","[AdachiRika, ShirasuJin]","[Mitarai, Yo, is, a, career, woman, who, works...",mitarai yo is a career woman who work for a sh...
233,Reply 1997,South Korea,Drama,2012,8.5,"[Comedy, Romance, Life]","[HighSchool, 1990s, FirstLove, FriendsToLovers...","[JungEunJi, SeoInGuk, LeeHoWon, ShinSoYool, Eu...","[Set, in, the, 1990s,, the, drama, centers, ar...","set in the 1990s, the drama center around a fe..."
1571,Strongest Deliveryman,South Korea,Drama,2017,7.9,"[Business, Comedy, Romance, Life]","[Debt, SecondaryCouple, StrongFemaleLead, Nice...","[GoKyungPyo, ChaeSooBin, KimSeonHo, GoWonHee]","[Choi, Kang, Soo, is, a, deliveryman., In, spi...",choi kang soo is a deliveryman. in spite of hi...
2074,Best Mistake,South Korea,Drama,2019,7.7,"[Comedy, Romance, Youth, Drama]","[HighSchool, LoveTriangle, CharacterDevelopmen...","[KangYul, LeeEunJae, YoonJunWon, ParkEHyun]","[To, get, a, boy, from, her, past, to, leave, ...","to get a boy from her past to leav her alone, ..."

## 3rd recommendor

In [174]:
df_3=df_2

In [175]:
df_3

,Title,Country,Year,Ratings,Tag
0,Hidden Love,China,2023,9.2,Comedy Romance Youth CaringMaleLead SecretCrus...
1,Move to Heaven,South Korea,2021,9.2,Life Drama Uncle-NephewRelationship Autism Dea...
2,Nirvana in Fire,China,2015,9.1,Military Historical Drama Political TragicPast...
3,Weak Hero Class 1,South Korea,2022,9.1,Action Youth Drama Violence Friendship Bromanc...
4,Hospital Playlist Season 2,South Korea,2021,9.1,Romance Life Drama Medical MultipleMains Band ...
...,...,...,...,...,...
4988,In a Relationship,Thailand,2022,6.8,Romance GayMaleLead ShortLengthSeries WebSerie...
4989,In Love With a Rich Girl,Taiwan,2004,6.8,Romance Sismance MultipleCouples RichesToRags ...
4990,My Mate Match,Thailand,2021,6.8,Comedy Romance Drama Cohabitation GayRomance L...
4991,Ghost Runner,Thailand,2020,6.8,Thriller Mystery Romance Supernatural Ghost In...
4992,Orange Marmalade,South Korea,2015,6.8,Historical Romance Drama Supernatural Interspe...

In [176]:
tfidf = TfidfVectorizer()
genre_tfidf = tfidf.fit_transform(df_3['Tag'])

In [177]:
genre_tfidf

<4993x8761 sparse matrix of type '<class 'numpy.float64'>'
	with 79737 stored elements in Compressed Sparse Row format>

In [178]:
similarity=cosine_similarity(genre_tfidf)

In [179]:
def drama_recommend(drama):
    drama_index=df_2[df_3.Title==drama].index[0]
    distance=similarity[drama_index]
    drama_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[0:6]
#     print(drama_list)
#     for i in drama_list:
#         print(df_copy.iloc[i[0]])
    nearest_drama = pd.DataFrame([df.iloc[i[0]] for i in drama_list])
    return nearest_drama

In [180]:
drama_recommend('Itaewon Class')

,Title,Country,Type,Year,Ratings,Genre,Tags,Actors,Synopsis,exp1
262,Itaewon Class,South Korea,Drama,2020,8.4,"[Business, Romance, Life, Drama]","[Revenge, TimeSkip, SmartFemaleLead, FemaleCha...","[ParkSeoJoon, KimDaMi, KwonNaRa, YooJaeMyung]","[Park, Saeroyi's, life, has, been, turned, ups...",park saeroyi' life ha been turn upsid down aft...
221,What's Wrong with Secretary Kim,South Korea,Drama,2018,8.5,"[Business, Comedy, Romance]","[Boss-EmployeeRelationship, RichMaleLead, Adap...","[ParkMinYoung, ParkSeoJoon]","[The, series, revolves, around, the, narcissis...",the seri revolv around the narcissist lee youn...
603,Pegasus Market,South Korea,Drama,2019,8.2,"[Business, Comedy, Drama]","[AdaptedFromAWebtoon, EccentricMaleLead, Teamw...","[KimByungChul, LeeDongHwi]","[""Cheap, Cheonlima, Mart"", tells, the, story, ...","""cheap cheonlima mart"" tell the stori of emplo..."
2272,Backstreet Rookie,South Korea,Drama,2020,7.7,"[Action, Business, Comedy, Romance]","[HardworkingFemaleLead, BadassFemaleLead, Boss...","[JiChangWook, KimYooJung, HanSunHwa, DoSangWoo...","[Jung, Saet, Byul, is, a, 22-year-old,, beauti...","jung saet byul is a 22-year-old, beauti four-d..."
102,Misaeng: Incomplete Life,South Korea,Drama,2014,8.7,"[Business, Life, Drama]","[WorkplaceAbuse, Teamwork, AdaptedFromAWebtoon...","[YimSiWan, LeeSungMin, KangSoRa, KangHaNeul, B...","[Jang, Geu, Rae, has, played, the, game, of, G...",jang geu rae ha play the game of go sinc he wa...
3905,Love Actually,China,Drama,2017,7.3,"[Business, Romance, Life, Drama]","[WorkplaceSetting, GeniusMaleLead, WorkplaceRo...","[JoeChen, TongDaWei, WangYiBo]","[Ding, Ren, Jian, is, a, married, man, with, a...",ding ren jian is a marri man with a child. he ...

In [181]:
drama_recommend("Moment at Eighteen")

,Title,Country,Type,Year,Ratings,Genre,Tags,Actors,Synopsis,exp1
1013,Moment at Eighteen,South Korea,Drama,2019,8.0,"[Comedy, Romance, Life, Drama]","[FirstLove, HighSchool, ShyMaleLead, LoveTrian...","[OngSeongWu, KimHyangGi, ShinSeungHo, KangKiYo...","[Transfer, student, Jun, Woo, has, no, interes...",transfer student jun woo ha no interest in sch...
894,A-Teen,South Korea,Drama,2018,8.1,"[Comedy, Romance, Life, Youth]","[WebSeries, MultipleMains, SecretCrush, CalmFe...","[ShinYeEun, LeeNaEun, KimSooHyun, KimDongHee, ...","[People, say, that, 18, is, a, carefree, age,,...","peopl say that 18 is a carefre age, but all th..."
3878,More Than Friends,South Korea,Drama,2020,7.3,"[Comedy, Romance, Life, Drama]","[MultipleCouples, FirstLove, LoveTriangle, Unr...","[OngSeongWu, ShinYeEun, KimDongJun, AhnEunJin,...","[Ten, years, ago,, Kyung, Woo, Yeon, was, as, ...","ten year ago, kyung woo yeon wa as innoc and c..."
725,Long Vacation,Japan,Drama,1996,8.2,"[Music, Romance, Life, Drama]","[FriendsToLovers, Cohabitation, OlderWoman/You...","[KimuraTakuya, YamaguchiTomoko]","[Sena, is, a, college, music, graduate, who, d...",sena is a colleg music graduat who dream of be...
1524,Sweet Revenge,South Korea,Drama,2017,7.9,"[Comedy, Romance, Youth, Fantasy]","[HighSchool, SchoolBullying, Revenge, NiceMale...","[KimHyangGi, Lomon, ChaEunWoo, KimHwanHee]","[This, web, drama, is, a, teen, fantasy, drama...",thi web drama is a teen fantasi drama about a ...
3051,Failing in Love,South Korea,Drama,2019,7.5,"[Romance, Life, Youth, Drama]","[HighSchool, WebSeries, LoveTriangle, SmartFem...","[SonSangYeon, YangHyeJi, ShinYoonSeop]","[Suffering, from, a, separation, anxiety, diso...","suffer from a separ anxieti disorder, kang pa ..."

In [183]:
df_copy.to_csv("./data/recommend/recommend.csv")